export default {
	login: 'opiyoxbenji',
	id: 123545485,
	node_id: 'U_kgDOB10njQ',
	avatar_url: 'https://avatars.githubusercontent.com/u/123545485?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/opiyoxbenji',
	html_url: 'https://github.com/opiyoxbenji',
	followers_url: 'https://api.github.com/users/opiyoxbenji/followers',
	following_url:
		'https://api.github.com/users/opiyoxbenji/following{/other_user}',
	gists_url: 'https://api.github.com/users/opiyoxbenji/gists{/gist_id}',
	starred_url:
		'https://api.github.com/users/opiyoxbenji/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/opiyoxbenji/subscriptions',
	organizations_url: 'https://api.github.com/users/opiyoxbenji/orgs',
	repos_url: 'https://api.github.com/users/opiyoxbenji/repos',
	events_url: 'https://api.github.com/users/opiyoxbenji/events{/privacy}',
	received_events_url:
		'https://api.github.com/users/opiyoxbenji/received_events',
	type: 'User',
	site_admin: false,
	name: 'Opiyo Benjamin Paul',
	company: null,
	blog: '',
	location: ' Kampala Uganda',
	email: 'opiyosbenji@gmail.com',
	hireable: null,
	bio: null,
	twitter_username: 'opiyoxbenji',
	public_repos: 6,
	public_gists: 0,
	followers: 100,
	following: 3,
	created_at: '2023-01-25T09:15:49Z',
	updated_at: '2023-03-30T17:37:07Z',
};
